### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'toLowerCase')`

### ISSUE THREAD

**Issue by zxy1882** [neptune-mutual-blue/app.neptunemutual.com#1011]
## URL
  
https://test.neptunemutual.com/pools/staking

## Error

```
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at https://test.neptunemutual.com/_next/static/chunks/pages/_app-ebc0f192a0a32d7a.js:1:1237267
    at V (https://test.neptunemutual.com/_next/static/chunks/pages/pools/staking-8cd3d283e5567c6f.js:1:1699)
    at oo (https://test.neptunemutual.com/_next/static/chunks/framework-79bce4a3a540b080.js:1:59417)
    at Wo (https://test.neptunemutual.com/_next/static/chunks/framework-79bce4a3a540b080.js:1:68984)
    at Ku (https://test.neptunemutual.com/_next/static/chunks/framework-79bce4a3a540b080.js:1:112708)
    at Li (https://test.neptunemutual.com/_next/static/chunks/framework-79bce4a3a540b080.js:1:98958)
    at Ni (https://test.neptunemutual.com/_next/static/chunks/framework-79bce4a3a540b080.js:1:98886)
    at Pi (https://test.neptunemutual.com/_next/static/chunks/framework-79bce4a3a540b080.js:1:98749)
    at bi (https://test.neptunemutual.com/_next/static/chunks/framework-79bce4a3a540b080.js:1:95715)
    at https://test.neptunemutual.com/_next/static/chunks/framework-79bce4a3a540b080.js:1:45209
```

## Device data

```json
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
```

**Comment by rupak-nm** [comment]
@zxy1882 can u give some more detailed steps to reproduce the issue, if any?
Do u get this issue anytime u visit this page or navigate through other page?
